# Generated by Django 2.2 on 2021-05-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210415_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pro_pic',
            field=models.ImageField(default='profile1.png', upload_to=''),
        ),
    ]
