# Generated by Django 2.2 on 2021-05-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210530_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Student'),
        ),
    ]
